from minecraft.core import *


Minecraft = Minecraft (
    settings=Minecraft.Settings(
        directory='./',
        description='generated by Butter\'s compiler',
        project_name='untitled',
        prefix_generated=str(
            'prefix_'
        )
    )
)


@Commands.function('load')
def main():
    sco = Scoreboard('main')
    sco.hide()


Minecraft.compile()
