"""
Open source project by ButterSss
"""

from __future__ import annotations

from pyKiwi import compiler
from pyKiwi import minecraft
from pyKiwi.types import score
from pyKiwi.types import scoreboard

import types
import dataclasses
import typing


class Reference:
    def __new__(cls) -> typing.Any:
        return super(Reference, cls).__new__(cls)


Minecraft: minecraft.Minecraft = Reference()
Score: typing.Type[score.Score] = Reference()
Scoreboard: typing.Type[scoreboard.Scoreboard] = Reference()


class PyKiwi:
    """
    Contains all other classes and handle compiling
    """
    _init_locals: typing.Dict[str, typing.Any]
    _init_module: types.ModuleType
    Compiler: compiler.Compiler
    Minecraft: minecraft.Minecraft
    Score: typing.Type[score.Score]
    Scoreboard: typing.Type[scoreboard.Scoreboard]

    @dataclasses.dataclass
    class Settings:
        directory: str
        description: str
        project_name: str
        version: str
    settings: Settings

    def __init__(self, local: typing.Dict[str, typing.Any], *,
                 directory: str = './',
                 description: str = 'generated by Butter\'s compiler',
                 project_name: str = 'untitled',
                 version: str = '1.19.2'
                 ):
        self._init_locals = local
        self.settings = self.Settings(
            directory=directory,
            description=description,
            project_name=project_name,
            version=version
        )
        self.Compiler = compiler.Compiler(self)
        self.Minecraft = minecraft.Minecraft(self)
        self.Score = score.getScore(self)
        self.Scoreboard = scoreboard.getScoreboard(self)
        if self._init_module in self._init_locals:
            self._setLocalValue(self._init_module.__dict__, Minecraft, self.Minecraft)
            self._setLocalValue(self._init_module.__dict__, Score, self.Score)
            self._setLocalValue(self._init_module.__dict__, Scoreboard, self.Scoreboard)
        else:
            self._setLocalValue(self._init_locals, Minecraft, self.Minecraft)
            self._setLocalValue(self._init_locals, Score, self.Score)
            self._setLocalValue(self._init_locals, Scoreboard, self.Scoreboard)

    @staticmethod
    def _setLocalValue(scope: typing.Dict[str, typing.Any], ref: typing.Any, new_value: typing.Any):
        for key, value in scope.items():
            if value is ref:
                scope[key] = new_value
                return
