"""
Open source project by ButterSss
"""

from __future__ import annotations

from PyKiwi import minecraft
from PyKiwi.types import score
from PyKiwi.types import scoreboard

import types
import dataclasses
import typing


class Reference:
    def __new__(cls) -> typing.Any:
        return super(Reference, cls).__new__(cls)


Minecraft: minecraft.Minecraft = Reference()
Score: typing.Type[score.Score] = Reference()
Scoreboard: typing.Type[scoreboard.Scoreboard] = Reference()


class PyKiwi:
    """
    Contains all other classes and handle compiling
    """
    _init_module: types.ModuleType
    Minecraft: minecraft.Minecraft
    Score: typing.Type[score.Score]
    Scoreboard: typing.Type[scoreboard.Scoreboard]

    @dataclasses.dataclass
    class Settings:
        directory: str
        description: str
        project_name: str
        version: str
    _settings: Settings

    def __init__(self, *,
                 directory: str = './',
                 description: str = 'generated by Butter\'s compiler',
                 project_name: str = 'untitled',
                 version: str = '1.19.2'
                 ):
        self._settings = self.Settings(
            directory=directory,
            description=description,
            project_name=project_name,
            version=version
        )

        self.Minecraft = minecraft.Minecraft(self)
        self._setLocalValue(self._init_module.__dict__, Minecraft, self.Minecraft)
        self.Score = score.getScore(self)
        self._setLocalValue(self._init_module.__dict__, Score, self.Score)
        self.Scoreboard = scoreboard.getScoreboard(self)
        self._setLocalValue(self._init_module.__dict__, Scoreboard, self.Scoreboard)

    @staticmethod
    def _setLocalValue(scope: typing.Dict[str, typing.Any], ref: typing.Any, new_value: typing.Any):
        for key, value in scope.items():
            if value is ref:
                scope[key] = new_value
                return

    def use_prefix(self) -> PyKiwi:
        return self

    def compile(self) -> PyKiwi:
        return self
